apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app
  labels: {}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sample-app.apps.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              number: 80
  tls:
  - hosts:
    - sample-app.apps.example.com
    secretName: myapp-tls
